### PR TITLE
added browser to package.json, resolves #1102

### LINKED ISSUE #1102: Consider including browser flag in package.json
Want to set the `browser` field to either the dist/handlebars file or lib/handlebars to avoid issues with require.extension code being included on the client.

Should look at using `browser` as an object rather than a string:
https://github.com/defunctzombie/node-uuid/blob/master/package.json#L30

This might let us handle the runtime and the full library.

### PR DESCRIPTION
**Pull request by ouijan**
Before creating a pull-request, please check https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md first.

Generally we like to see pull requests that

- [ ] Please don't start pull requests for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Maintain the existing code style
- [ ] Are focused on a single change (i.e. avoid large refactoring or style adjustments in untouched code if not the primary goal of the pull request)
- [ ] Have good commit messages
- [ ] Have tests
- [ ] Have the [typings](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (lib/handlebars.d.ts) updated on every API change. If you need help, updating those, please mention that in the PR description.
- [ ] Don't significantly decrease the current code coverage (see coverage/lcov-report/index.html)
- [ ] Currently, the `4.x`-branch contains the latest version. Please target that branch in the PR.

### CODE REVIEW

**Comment by nknapp** [comment]
Released in 4.1.2-0

**Comment by nknapp** [comment]
I have release this change with a pre-release version so that people can test it before it becomes a real release.

**Comment by nknapp** [comment]
@ouijan have you been able to test this fix with your setup? 

I am a bit irritated because @kpdecker gave it the milestone 5.0.0. This might indicate a breaking change which means somebody's build will break when I release it in the next patch version.

I actually think about delaying this until we have some proper integration tests set up for various build scenarios. That said: Could you provide a minimal setup that reflects the way you are using Handlebars.

I am currently setting up a framework for that purpose in the main repository.

**Comment by ouijan** [comment]
Hey @nknapp. 
Sorry, I didn't mean to rush this into version 4's release cycle. 

I set up these to example intellisense failing to resolve handlebars. I'm not familiar with stackblitz but in our codebase this error causes compilation to fail as well. I'll have a play and see if I can get this reflected in these stackblitz examples too.

- Handlebars (4.0.14) - Can't Resolve
  https://stackblitz.com/edit/angular-jcacqv
- Handlebars (4.1.2) - Resolves
  https://stackblitz.com/edit/angular-awspdw

**Comment by nknapp** [comment]
There are no typings included in version 4.0.x This may be the problem. Btw. This PR is included in 4.2.0, not 4.1.2, I don't know why `generator-release` has release 4.1.2-0 when I made the prerelease. But 4.1.2 is without the browser-properties.

**Comment by nknapp** [comment]
You can try to include an integration test in the [integration-testing](https://github.com/wycats/handlebars.js/tree/master/integration-testing) directory.
Just add a project and a "test.sh" to run the test.

**Pull request merged**
