### PR TITLE
Use yargs

### LINKED ISSUE #1179: Optimist is deprecated
You can use https://github.com/bcoe/yargs as an alternative

### PR DESCRIPTION
**Pull request by TrySound**
Fix #1179

### CODE REVIEW

**Comment by webmaster128** [comment]
hi all and thanks for making handlebars!

I see this more than 3 year old patch but I still have optimist in my dependencies. Did this not make it into the 4.x release at all?

**Comment by nknapp** [comment]
No, @wycats wants a spec before adding new features (#1277) so I am currently only fixing bugs, security issues and make improvements to the build-environment and code cleansiness...

I'm not sure if any compability issues arise by using yargs, so I'll not add it in 4.x.

I'm trying to move development back to the master-branch, so I may attempt to release 5.0 with the changes on master (#1566) . But I am in no rush.

Is there are particular reason why you ask about this?

**Comment by webmaster128** [comment]
> Is there are particular reason why you ask about this?

I just found this super old dependency in my tree

```
wordwrap@~0.0.2:
  version "0.0.3"
```

which happens to be pulled in by

```
optimist@^0.6.1:
  version "0.6.1"
```

which appears to be unmaintained for 6 years. My feeling was those should not be in my dependency tree these days. Then I found #1179 and this PR, which were closed/merged so long ago.

So yeah, no strictly required but it would be a nice cleanup

**Comment by serhiyzablotskiy** [comment]
I also have optimist in dependencies of handlebars@4.7.3. And now it has vulnerability with minimist.
Screen Shot 2020-03-27 at 4 39 16 PM

**Comment by webmaster128** [comment]
@serhiyzablotskiy see https://github.com/wycats/handlebars.js/pull/1662 for the latest discussion on that topic

**Pull request merged**
