### PR TITLE
Added -w, --watch option to the handlebars CLI

### PR DESCRIPTION
**Pull request by m-ahmadi**
Watch option for the handlebars CLI.
It watches for changes on the input file(s) / dir(s), and performs reprecompilation on changes to them.
I used the 'chokidar' package for watching files and folders, and the 'color' package for outputing nice looking messages to the console.

### CODE REVIEW

**Comment by m-ahmadi** [comment]
If you don't want the ES6 stuff, tell me to replace them.

**Comment by nknapp** [comment]
I personally feel a bit controversial about this request. "chokidar" adds another 2MB to the total size of Handlebars. I have a few projects that use Handlebars and I am constantly trying to *reduce* the size of those projects. 
I think that such a development tool should be in a separate project.

**Comment by stevenvachon** [comment]
This should probably be handled with [npm-watch](https://npmjs.com/npm-watch), since it can restart the process, which is particularly useful if the current process is not yet complete.

**Comment by m-ahmadi** [comment]
I made another pr and changed it from two commits into one, can you guys please copy-paste your comments there?

**Pull request closed without merging**
