### PR TITLE
Add indexPlusOne support

### PR DESCRIPTION
**Pull request by cfjedimaster**

### CODE REVIEW

**Comment by Ghazgkull** [comment]
Surprised and disappointed that Handlebars doesn't provide a one-based index out of the box. It's such a common and obvious need. Judging by the fact that #250 was locked, it looks like this issue is blocked by a personal desire to "win" the discussion. 👎

**Comment by stevenvachon** [comment]
Surprised? If `@index` were 1 and not 0, `{{#if @index}}` would never be false. Have you used mustache?

**Comment by cfjedimaster** [comment]
@stevenvachon to be clear - we're asking about support for a *new* var, indexPlusOne, or some such, that would not change the behavior of index.

**Comment by stevenvachon** [comment]
@cfjedimaster my response was to @Ghazgkull -- I should've put that in.

**Comment by cfjedimaster** [comment]
Fair enough.

**Comment by Ghazgkull** [comment]
This discussion (and the others like it that have been locked) isn't about changing @index to be one-based. @cfjedimaster understood the context.

**Comment by ErisDS** [comment]
Just to throw 2c in here - Ghost has its own version of each, [foreach](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/foreach.js#L76). Amongst other things it has this feature, and we called it `{{@number}}`.

**Pull request closed without merging**
