### PR TITLE
test: add test for NodeJS compatibility

### PR DESCRIPTION
**Pull request by nknapp**
The test is a simple addition to the existing tests. It should ensure
that the built Handlebars artifact only uses language features that are
available in old versions of NodeJS. A simple program and the
precompiler are started with NodeJS 0.10 to 11

Before creating a pull-request, please check https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md first.

Generally we like to see pull requests that

- [x] Please don't start pull requests for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [x] Maintain the existing code style
- [x] Are focused on a single change (i.e. avoid large refactoring or style adjustments in untouched code if not the primary goal of the pull request)
- [x] Have good commit messages
- [x] Have tests
- [x] Have the [typings](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (lib/handlebars.d.ts) updated on every API change. If you need help, updating those, please mention that in the PR description.
- [x] Don't significantly decrease the current code coverage (see coverage/lcov-report/index.html)
- [x] Currently, the `4.x`-branch contains the latest version. Please target that branch in the PR.

### CODE REVIEW

**Comment by hady2** [comment]
Hadi Contracting Company Decoration and Dyes

**Comment by hady2** [comment]
Hadi Contracting Company Decoration and Dyes

**Comment by hady2** [comment]
Merged #1501 into 4.x.

**Comment by nknapp** [comment]
@hady2 I deleted your comments because they read like spam and did not make any sense.

**Pull request merged**
