### PR TITLE
Update README.markdown with a new project link (openVALIDATION)

### PR DESCRIPTION
**Pull request by thecodemonkey**
added a new Project (openVALIDATION) to the section  "Handlebars in the Wild"

Before creating a pull-request, please check https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md first.

Generally we like to see pull requests that

- [x] Please don't start pull requests for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Maintain the existing code style
- [x] Are focused on a single change (i.e. avoid large refactoring or style adjustments in untouched code if not the primary goal of the pull request)
- [x] Have good commit messages
- [ ] Have tests
- [ ] Have the [typings](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (lib/handlebars.d.ts) updated on every API change. If you need help, updating those, please mention that in the PR description.
- [x] Don't significantly decrease the current code coverage (see coverage/lcov-report/index.html)
- [ ] Currently, the `4.x`-branch contains the latest version. Please target that branch in the PR.

### CODE REVIEW

**Comment by nknapp** [comment]
I have had a brief look, but I haven't grasped how you are using handlebars. Could you explain shortly, what you are using it for?

**Comment by thecodemonkey** [comment]
we have developed a natural language compiler for validation rules. It can generate program code from validation rules written in english or german. For code generation we use the handlebars framework. Here are our generator templates:

https://github.com/openvalidation/openvalidation/tree/master/openvalidation-generation/src/main/resources

**Comment by thecodemonkey** [comment]
Danke Nils!

**Comment by nknapp** [comment]
bitte

**Pull request merged**
