### PR TITLE
Perf: replace async with neo-async

### PR DESCRIPTION
**Pull request by dfederm**
neo-async is a drop-in replacement for async which is faster.

### CODE REVIEW

**Comment by dfederm** [comment]
Comparing the benchmarks with the [last ci build](https://travis-ci.org/wycats/handlebars.js/jobs/348995518) (using scaled values in case hardware is different)

Last CI build:
```
scaled              [secure]          compat              dust                eco                 mustache            
------------------------------------------------------------------------------------------------------------------------
arguments           3.23                3.01                                                                            
array-each          5.31                2.47                2.67                1.36                0.90                
array-mustache      3.96                1.92                                                                            
complex             1.19                0.48                0.71                0.57                0.21                
data                2.12                1.45                                                                            
depth-1             1.96                1.87                                    1.44                0.56                
depth-2             0.40                0.39                                    0.74                0.05                
object-mustache     7.75                1.12                                                                            
object              7.17                0.96                4.30                1.85                1.77                
partial-recursion   0.17                0.08                0.01                                    0.79                
partial             1.79                0.50                1.64                                    0.43                
paths               10.19               6.57                2.34                1.42                0.90                
string              14.24               13.02               8.98                7.38                99.21               
subexpression       2.41                2.39                                    3.71                                    
variables           13.01               11.03               6.28                2.04                2.94                
```

My PR build:
```
scaled              handlebars          compat              dust                eco                 mustache            
------------------------------------------------------------------------------------------------------------------------
arguments           3.04                2.63                                                                            
array-each          4.29                1.92                2.23                1.33                0.70                
array-mustache      2.99                1.38                                                                            
complex             0.86                0.33                0.48                0.48                0.11                
data                1.52                1.04                                                                            
depth-1             1.58                1.54                                    1.40                0.52                
depth-2             0.35                0.32                                    0.65                0.02                
object-mustache     5.47                0.95                                                                            
object              6.71                1.16                4.25                1.88                1.34                
partial-recursion   0.16                0.07                0.01                                    0.73                
partial             1.50                0.38                1.33                                    0.52                
paths               10.07               6.64                2.62                1.60                1.03                
string              11.86               9.84                6.08                6.52                98.43               
subexpression       1.88                1.97                                    2.89                                    
variables           9.65                8.47                5.54                1.77                2.13      
```

**Comment by nknapp** [comment]
I'll close this as I have made my own commit... It wasn't in the README at the time this PR was created, but new PRs should always be based on the `4.x`-branch. Master is not going to be published anytime soon, I fear.

**Comment by hady2** [comment]
Merged #1501 into 4.x.

**Comment by hady2** [comment]
#1501

**Pull request closed without merging**
