### PR TITLE
move uglify-js to dependencies

### LINKED ISSUE #1391: `uglify-js` is unconditionally imported, but only listed as optional dependency
This is causing https://github.com/ember-cli/ember-cli/issues/7371, where people are using `npm` to install `handlebars` as a transitive dependency but apparently `npm` is not installing the optional `uglify-js` dependency (anymore?) which makes the import fail.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #1391

### CODE REVIEW

**Comment by nknapp** [comment]
Personally, I'm in favour of keeping the dependency optional and handle the missing library case. It greatly reduces the amount of dependencies and downloaded megabytes if you don't need the precompiler. Opinions?

**Comment by rwjblue** [comment]
Agreed, but with the move to ES modules how do we conditionally import?

**Comment by nknapp** [comment]
I would make an execption here. It may make sense to move to completely towards es6-modules, but if they lack support for essential features, we should omit them when we can't use them.

I would suggest using `require('uglify-js')` instead and adding a lengthy comment, with the reason for not using es6.

**Comment by nknapp** [comment]
I made a PR here: #1394

**Comment by nknapp** [comment]
I'm closing this in favor of #1394

**Pull request closed without merging**
