### PR TITLE
update babel dependency to babel 6

### PR DESCRIPTION
**Pull request by marado**
On Babel 6, loose is enabled in a different way. This PR updates it.
More info: https://github.com/babel/babel/issues/2746

### CODE REVIEW

**Comment by marado** [comment]
work on this PR still incomplete:
```
handlebars.js/dist/cjs/precompiler.js:88
    let { template: path, root } = queue.shift();
        ^

SyntaxError: Unexpected token {
```

**Comment by nknapp** [comment]
Do you have an idea, why the tests fail?

**Comment by marado** [comment]
Not really, I stopped at the error in my previous comment, without debugging it, and didn't have time to get back to this issue since.

**Comment by nknapp** [comment]
Closing this for now. New attempts to upgrade webpack an babel will certainly be done in other PRs.

**Pull request closed without merging**
