### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by atomictag**
Add [incremental-bars](https://github.com/atomictag/incremental-bars) to the list of projects using Handlebars

### CODE REVIEW

**Comment by zpr0571** [comment]
sorry，no！
 
 
------------------ Original ------------------

**Comment by nknapp** [comment]
@zpr0571 what do you mean by "sorry, no!" ?

**Comment by nknapp** [comment]
I assume the response by @zpr0571 was a mistake.

**Comment by atomictag** [comment]
Thanks!

**Pull request merged**
