### PR TITLE
Use `import` instead of `module`

### PR DESCRIPTION
**Pull request by seanpdoyle**
* export Helpers as default export in `handlebars/compiler/base`

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@mmun would you mind merging this into your branch so we can move forward with https://github.com/emberjs/ember.js/pull/10853

**Comment by stefanpenner** [comment]
`import * as helpers from '...'`

**Comment by seanpdoyle** [comment]
@stefanpenner 

```js
import * as Helpers from "./helpers";
```

results in 

```
Warning: Line 4: Unexpected token * Use --force to continue.
```

The toolchain doesn't support that syntax

**Comment by kpdecker** [comment]
Can you explain the reason for this change?

**Comment by kpdecker** [comment]
Looks like this is trying to hack around #855 but is introducing more tech debt. Not really a fan of this but would love to hear the argument for it.

**Comment by seanpdoyle** [comment]
@kpdecker you're right about that.

I'd certainly prefer to use `import * as Helpers from "./helpers";`.

This change is motivated by https://github.com/emberjs/ember.js/pull/10853#issuecomment-91089580

What would it take to support that syntax (given the change in ES6 landscape since #855)

**Comment by stefanpenner** [comment]
> import * as Helpers from "./helpers";

it is valid, we will need to upgrade the transpiler to support this (now or later)

**Comment by seanpdoyle** [comment]
@kpdecker could we update https://github.com/kpdecker/es6-module-packager to use babel?

**Comment by kpdecker** [comment]
That could be an option. es6-module-transpiler was a no go as it generated code that wouldn't run under IE. I don't have time to look into that now but I'd be glad to look at a pull request over there.

**Comment by stefanpenner** [comment]
Use the es6modules transpiler we have in the ember cli repo. It's Esperanto under the hood with flags enabled or enable able for es3 safety. It is also ultimately what ember core is currently build with

**Comment by seanpdoyle** [comment]
@stefanpenner do you mean https://github.com/ember-cli/broccoli-es6modules?

Does that introduce a broccoli dependency to the build process?

**Comment by stefanpenner** [comment]
If you don't want to do that. Look at how it calls Esperanto under the hood and drop Esperanto in here. There may even be an appropriate plugin for this build system.

Just make sure to call Esperanto with the same flags ember-cli does. So es3 safety requirement is met.

**Comment by kpdecker** [comment]
Closing in favor of #998

**Comment by seanpdoyle** [comment]
:clap:

**Pull request closed without merging**
